[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/awslabs/aws-lambda-go-api-proxy"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true